Build/#10
Hoobig0/tmbm-backend pull request #12
Opened 2024-05-12 08:35 UTC by BOYOUNG-KANG

## 연관된 이슈
resolve #10 

## 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- MySQL 선택 이유
  - 보편적으로 많이 사용되는 관계형 DB이므로 안정적인 데이터베이스 입니다.
  - OLTP 환경에서 안정적인 성능을 보여주는 DB입니다.
  - 최근 정필, 교현님과 함께 mysql 스터디를 진행하면서 학습한 내용을 적용하여 잘 쓰고 싶어서 선택하게 되었습니다.
- mysql과 hibernate-spatial, h2gis 디펜던시 추가
- application-local.yml, application-dev.yml 설정에 데이데이터베이스 관련 설정 추가
  - ddl-auto : 기본 설정을 update로 하고 도메인 생성 시 create를 사용하여 생성된 도메인에 해당하는 테이블을 생성할 수 있도록 합니다.
  - schema.sql : H2GIS에 세팅에 필요한 초기 실행 SQL 문 추가

2024-05-12 09:02 UTC, rygus9 commented
H2에 콘솔도 넣어주세용!

2024-05-12 14:44 UTC, rygus9 approved these changes

2024-05-15 07:00 UTC, mrlee7 requested changes
확인이 필요한 부분들이 있어, 코멘트 드렸습니다.  
고생 많으셨습니다. 감사합니다 🙇

2024-05-15 07:00 UTC, mrlee7 commented on build.gradle
> +	runtimeOnly 'com.mysql:mysql-connector-j'
In-memory DB / MySQL DB 를 분리하는게 좋을지 고민이 되네요.. 🤔  
일단은 유즈케이스가 더 쌓일때까지 고민을 미뤄보기로 해요 !_! 감사합니다 보영님 👍

2024-05-15 14:03 UTC, BOYOUNG-KANG reviewed
세세한 리뷰 감사드립니다! 🙇‍♀️

2024-05-15 14:03 UTC, BOYOUNG-KANG commented on src/main/resources/application-local.yml
> +      ddl-auto: ${jpa.ddl-auto}
이 부분에 대한 설명이 부족했네요! 
기본값으로 update를 설정하여 칼럼 변경 등의 변경사항을 적용할 수 있도록 하였고, 후에 저희 도메인이 생성시에는 create을 사용하여 생성된 도메인에 해당하는 테이블을 생성할 수 있도록 할 생각입니다!

2024-05-15 14:03 UTC, BOYOUNG-KANG commented on src/main/resources/application-local.yml
> +    url: ${h2.url}
좋은 의견 감사합니다! 👍
environment에 두는 것이 가독성이나 수정 부분에서 불편함이 있었는데 string 그대로 사용하는 방식으로 수정해보겠습니다!

2024-05-15 22:13 UTC, mrlee7 approved these changes
고생 많으셨습니다 !  
감사해요 보영님 ;)

2024-05-16 13:37 UTC, merged