feat: 초기에 데이터 로드하기.
Hoobig0/tmbm-backend pull request #13
Opened 2024-05-18 08:35 UTC by rygus9

## 연관된 이슈

resolve #11

## 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

* ApplicationRunner를 이용해 로컬 환경에서 초기에 엑셀에 있는 데이터 로드하기.

## 스크린샷 (선택)

<img width="430" alt="스크린샷 2024-05-18 오후 5 31 51" src="https://github.com/Hoobig0/tmbm-backend/assets/52780207/8220ca4a-9736-4ba9-ae01-b6d5dba3e81b">

## 리뷰 요구사항 (선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. ex)메서드 이름 문의

* #7 과 레포지토리와 도메인이 겹쳐서 그 부분만 먼저 머지해와서 진행했습니다. 컨플릭트 위험이 있어서 테스트 코드는 #7 의 PR에서 진행하고자 합니다. (해당 작업은 보영님께서 작업하고 계십니다.) 다음번에 업무를 분장할 때에는 좀더 신중하게 분장하는게 좋을 것 같네요.

* 메서드 이름과 패키지 이름은 제가 끌리는대로 했습니다. 당당한 피드백 부탁드립니다.

* CommandRunner를 추천해주셨는데 ApplicationRunner가 에러 던질 필요도 없고, 인자를 좀 더 정리해서 준다는 장점이 있는거 같아서 추후 혹시 확장할 일이 있을 때를 대비해 ApplicationRunner를 적용했습니다.

2024-05-18 08:37 UTC, rygus9 commented on build.gradle
> +	implementation 'org.apache.poi:poi-ooxml:5.2.5'
fast-excel와 고민을 해봤었는데 apache.poi로 로드하는 속도가 그렇게 느리지 않아서 속도 때문에 아직 버전 1이 되지 않은 라이브러리를 선택하는 메리트가 떨어진다고 판단하여 apache.poi를 적용했습니다.

2024-05-18 08:40 UTC, BOYOUNG-KANG approved these changes
감사합니다 수고하셨습니다! 😆

2024-05-20 13:32 UTC, mrlee7 requested changes
rebase가 안되어 있는 것 같은데, 확인 부탁드립니다.
https://github.com/Hoobig0/tmbm-backend/pull/12 의 MR 커밋이 같이 들어가있네요 😄

2024-05-20 13:46 UTC, rygus9 commented
> rebase가 안되어 있는 것 같은데, 확인 부탁드립니다. #12 의 MR 커밋이 같이 들어가있네요 😄

요거 제가 작업을 하긴해야하니 build/#10에서 브랜치를 따서 작업 시작했었네요. 요거 수정해주겠습니다.

2024-05-20 13:48 UTC, rygus9 commented on src/main/resources/cctv.xlsx
저도 동의합니다. 다만 파이썬 스크립트 등으로 DML로 파싱하는 코드는 어떻게 관리하는게 좋을지 고민이 되네요.

2024-05-20 13:55 UTC, rygus9 commented on src/main/java/service/tmbmbackend/cctv/CCTV.java
> +@Entity(name = "cctv")
스네이크 케이스 찬성입니다. 해당 내용도 반영해두겠습니다.

2024-05-20 13:55 UTC, rygus9 commented on src/main/java/service/tmbmbackend/cctv/repository/CCTVRepository.java
> +@Repository
아 이 부분은 제가 좀더 주의를 기울였어야했는데 좋은 피드백 감사드립니다!

2024-05-20 13:58 UTC, rygus9 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:2.2.220'
사실 요 부분은 기존 build 작업 결과를 머지 땡겨온거라 자세히는 모릅니다... 제가 아는 선에서 답변드리자면 H2에 공간 인덱스 기능 확장을 위해 설치하는 orbisgis 라이브러리와 버전을 맞추기 위해서 버전을 명시한 걸로 알고 있습니다.

2024-05-20 13:58 UTC, rygus9 commented on src/main/java/service/tmbmbackend/cctv/bootstrap/LocalDataSetup.java
커밋 제목만 쓰는 사람이지만 바디도 써보도록 노력해보겠습니다.

2024-05-20 14:00 UTC, rygus9 commented on src/main/java/service/tmbmbackend/cctv/CCTV.java
> +        this.point = geometryFactory.createPoint(new Coordinate(x, y));
좋습니다~!

2024-05-20 14:01 UTC, rygus9 commented on src/main/java/service/tmbmbackend/cctv/bootstrap/LocalDataSetup.java
> +                double x = Double.parseDouble(row.getCell(11).getStringCellValue());
요런 피드백이! 트라이하고 난 이후에 정리가 부족했습니다. 파이썬 스크립트로 만들 때에는 해당 내용도 반영해두겠습니다~!

2024-05-25 05:58 UTC, rygus9 commented
일단 rebase해서 force push르 base를 변경했습니다. git branch 정책과 관련해서 feature 생성은 무조건 main에서 시작한다를 강제하고 가는게 좋겠네요. 그리고 다른 feat branch에서 머지 땡겨오는 거는 허용할지 고민을 조금 해보면 좋을 것 같아요. (아예 막아버리면 인과 관계에 놓인 작업들이 너무 블락 걸려버려서요)

2024-05-26 01:33 UTC, rygus9 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2:2.2.220'
요거 버저닝 제거하니깐 제대로 안돌아가더라구요. 아마 h2gis 사용하게 되면서 버전을 맞춰야해서 그런게 아닐까 싶습니다.

2024-05-26 01:51 UTC, rygus9 commented
- [x] excel 분석해서 로드 대신 SQL 로드
- [x] CCTV entity에 GeneratedValue(strategy = GenerationType.IDENTITY) 적용
- [x] CCTV 생성자에 Point 생성 로직 분리
- [x] 모듈형 디렉토리 구조에서 계층형 디렉토리 구조로 변경

커밋 메세지 작성과 함수명에 신경쓰며 작업 진행했습니다. 좋은 피드백 감사드립니다.
추가로 버저닝 관련해서 버저닝을 지우면 동작이 제대로 되지 않아 수정을 하진 않았습니다.
cc. @mrlee7  @BOYOUNG-KANG

2024-05-26 03:18 UTC, mrlee7 approved these changes
개인적인 코멘트 남겨두었습니다.  
이후 반영되어도 무관하여 Approve 드렸습니다 :) 
너무 고생 많으셨습니다 🙇

2024-05-26 03:18 UTC, mrlee7 commented on src/main/java/service/tmbmbackend/bootstrap/LocalDataSetup.java
> +        executeInsertSql();
- executeInsertSql 이라는 별개의 함수로 분리하신 사유가 궁금합니다 ! :) 
- args가 사용되지 않는 것 같습니다 ! 🤔 사용되지 않는다면 제거되어도 좋을 것 같습니다. 
- execute / insert 모두 행위이기 떄문에 `insertInitialData` 정도로 표현되어도 괜찮을 것도 같습니다 ! <- 이것은 개인적인 취향에서 제안드리는 바입니다 🙇

2024-05-26 03:18 UTC, mrlee7 commented on src/main/java/service/tmbmbackend/bootstrap/LocalDataSetup.java
> +        } catch (Exception e) {
IOException 부터 분기하는 것이 좋을 것도 같은데 !  
이번에는 우선 패스하시죠 !! 💙

2024-05-26 03:18 UTC, mrlee7 commented on src/main/java/service/tmbmbackend/entity/CCTV.java
> +    private Point createPoint(double x, double y) {
최고십니다 👍 
반영해주셔서 감사합니다 🙏

2024-05-26 05:26 UTC, rygus9 commented on src/main/java/service/tmbmbackend/bootstrap/LocalDataSetup.java
> +        } catch (Exception e) {
Java에서 Exception 처리를 어캐하는지 알아보는게 좋을 것 같네요. 다음에 좀더 알아보고 적용해보겠습니다!

2024-05-26 05:30 UTC, rygus9 commented on src/main/java/service/tmbmbackend/bootstrap/LocalDataSetup.java
> +        executeInsertSql();
작업했을 때에는 다른 데이터도 로드될 수 있겠다 싶어서 이런 식으로 분리했었는데요. 생각해보니 함수 이름을 저렇게 포괄적으로 지어버리면 분리한 의미가 없을 것 같네요. 음.. 그래도 함수명으로 run에서 실행하는 작업의 방향을 표현하는게 나을 것 같다는 생각이라 함수는 남겨둘까 합니다. 나머지 코멘트들은 반영해두겠습니다.

2024-05-26 05:31 UTC, rygus9 commented on src/main/java/service/tmbmbackend/bootstrap/LocalDataSetup.java
> +        executeInsertSql();
좋은 피드백 감사드립니다 🙇‍♂️

2024-05-26 05:35 UTC, merged